(function(g){var window=this;var Vua=function(a,b){var c=[];g.pm(b,function(a){var b;try{b=g.$D.prototype.o.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.ZD(b)&&c.push(a):c.push(a)},a);
return c},Wua=function(a,b){var c=Vua(a,b);
(0,g.F)(c,function(a){g.$D.prototype.remove.call(this,a)},a)},s9=function(a,b){g.AW.call(this,g.U("YTP_MDX_TITLE"),0,a,b);
this.W=a;this.B=!1;this.G={};this.V(a,"onMdxReceiversChange",this.H);this.V(a,"presentingplayerstatechange",this.H);this.H()},Xua=function(a){return a.H?a.F+((0,g.E)()-a.A)/1E3:a.F},Yua=function(){var a=g.BH;
Wua(a,a.g.Od(!0))},t9=function(a){g.dI.call(this,"ScreenServiceProxy");
this.Vc=a;this.o=[];this.o.push(this.Vc.$_s("screenChange",(0,g.z)(this.bQ,this)));this.o.push(this.Vc.$_s("onlineScreenChange",(0,g.z)(this.xM,this)))},u9=function(a){g.RH("cloudview",a)},Zua=function(a){u9("setApiReady_ "+a);
g.oa("yt.mdx.remote.cloudview.apiReady_",a,void 0)},v9=function(){return g.u("yt.mdx.remote.cloudview.instance_")},$ua=function(a){g.VG[a]&&(a=g.VG[a],(0,g.F)(a,function(a){g.TG[a]&&delete g.TG[a]}),a.length=0)},w9=function(){return g.u("yt.mdx.remote.connection_")},x9=function(a){g.oa("yt.mdx.remote.connectData_",a,void 0)},ava=function(a){g.oa("yt.mdx.remote.currentScreenId_",a,void 0)},y9=function(){return g.u("yt.mdx.remote.currentScreenId_")},A9=function(){if(!z9){var a=g.u("yt.mdx.remote.screenService_");
z9=a?new t9(a):null}return z9},B9=function(a){g.oa("yt.mdx.remote.cloudview.initializing_",a,void 0)},C9=function(){return!!g.u("yt.mdx.remote.cloudview.apiReady_")},D9=function(a){u9("setCastInstalled_ "+a);
g.DH("yt-remote-cast-installed",a)},E9=function(a){g.RH("cloudview",a)},bva=function(a,b){v9().init(a,b)},F9=function(){return!!g.EH("yt-remote-cast-installed")},cva=function(){u9("dispose");
var a=v9();a&&a.dispose();g.oa("yt.mdx.remote.cloudview.instance_",null,void 0);Zua(!1);(0,g.r2)(G9);G9.length=0},dva=function(){var a=window.document.createElement("a");
g.Sd(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Ua(a)},eva=function(a,b){var c=window.document.createElement("script");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
c.src="https://www.gstatic.com/cv/js/sender/v1/cast_sender.js";var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},fva=function(a){var b=g.SG();
if(b)if(b.clear(a),a)$ua(a);else for(var c in g.VG)$ua(c)},H9=function(){return g.u("yt.mdx.remote.channelParams_")||{}},J9=function(a){var b=w9();
x9(null);a||ava("");g.oa("yt.mdx.remote.connection_",a,void 0);I9&&((0,g.F)(I9,function(b){b(a)}),I9.length=0);
b&&!a?g.$G("yt-remote-connection-change",!1):!b&&a&&g.$G("yt-remote-connection-change",!0)},gva=function(){return g.u("yt.mdx.remote.connectData_")},K9=function(){var a=y9();
if(!a)return null;var b=A9().Td();return g.cI(b,a)},hva=function(a,b){D9(!0);
B9(!1);bva(a,function(a){a?(Zua(!0),g.ZG("yt-remote-cast2-api-ready")):(E9("Failed to initialize cast API."),D9(!1),g.FH("yt-remote-cast-available"),g.FH("yt-remote-cast-receiver"),cva());b(a)})},iva=function(){return F9()?v9()?v9().getCastSession():(E9("getCastSelector: Cast is not initialized."),null):(E9("getCastSelector: Cast API is not installed!"),null)},jva=function(){var a=dva(),b=window.document.getElementById(a),c=b&&g.RF(b,"loaded");
c||b&&!c||(b=eva(a,function(){g.RF(b,"loaded")||(g.SF(b,"loaded","true"),g.ZG(a),g.kF(g.za(fva,a),0))}))},kva=function(a){return(0,g.H)(a,function(a){return{key:a.id,
name:a.name}})},lva=function(){if(g.poa){var a=2,b=g.Gh(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;g.Lh("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",g.Ih,c)}},M9=function(a,b){y9();
K9()&&K9();ava(a.id);var c=new g.hJ(L9,a,H9());c.connect(b,gva());c.subscribe("beforeDisconnect",function(a){g.$G("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){w9()&&(w9(),J9(null))});
J9(c)},N9=function(){var a=g.iI();
if(!a)return null;var b=A9().Td();return g.cI(b,a)},O9=function(a){g.RH("remote",a)},P9=function(){var a=w9();
return!!a&&3!=a.getProxyState()},Q9=function(){C9()?v9().stopSession():E9("stopSession called before API ready.");
var a=w9();a&&(a.disconnect(1),J9(null))},mva=function(){var a;
a=A9().Vc.$_gos();var b=K9();b&&w9()&&(g.bI(a,b)||a.push(b));return kva(a)},S9=function(a,b){g.uG.call(this);
this.g=0;this.B=a;this.D=[];this.C=new g.nC;this.A=this.o=null;this.H=(0,g.z)(this.IK,this);this.F=(0,g.z)(this.Ck,this);this.G=(0,g.z)(this.HK,this);this.J=(0,g.z)(this.VK,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Qs,this),nva(this))):c=3;0!=c&&(b?this.Qs(c):g.kF((0,g.z)(function(){this.Qs(c)},this),0));
var d=iva();d&&R9(this,d);this.subscribe("yt-remote-cast2-session-change",this.J)},T9=function(a){return new g.XI(a.B.getPlayerContextData())},ova=function(a,b,c,d,e){var f=T9(a),k=e||f.listId;
d=d||0;var l={videoId:b,currentIndex:d};g.aJ(f,b,d);g.t(c)&&(g.ZI(f,c),l.currentTime=c);g.t(k)&&(l.listId=k);U9(a,"setPlaylist",l);e||V9(a,f)},nva=function(a){(0,g.F)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.D.push(this.B.subscribe(a,g.za(this.RM,a),this))},a)},pva=function(a){(0,g.F)(a.D,function(a){this.B.unsubscribeByKey(a)},a);
a.D.length=0},W9=function(a,b){50>a.C.Dc()&&g.pC(a.C,b)},X9=function(a,b,c){var d=T9(a);
g.ZI(d,c);-1E3!=d.g&&(d.g=b);V9(a,d)},U9=function(a,b,c){a.B.sendMessage(b,c)},V9=function(a,b){pva(a);
a.B.setPlayerContextData(g.bJ(b));nva(a)},R9=function(a,b){a.A&&(a.A.removeUpdateListener(a.H),a.A.removeMediaListener(a.F),a.Ck(null));
a.A=b;a.A&&(Y9("Setting cast session: "+a.A.sessionId),a.A.addUpdateListener(a.H),a.A.addMediaListener(a.F),a.A.media.length&&a.Ck(a.A.media[0]))},qva=function(a){var b=a.o.media,c=a.o.customData;
if(b&&c){var d=T9(a);b.contentId!=d.videoId&&Y9("Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;g.ZI(d,a.o.getEstimatedTime());V9(a,d)}else Y9("No cast media video. Ignoring state update.")},Y9=function(a){g.RH("CP",a)},Z9=function(a,b,c){return(0,g.z)(function(a){this.ac("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.ac("Retrying "+b+" using MDx browser channel."),U9(this,b,c))},a)},rva=function(a){var b=!1;
v9()||(a=new g.RI(a),a.subscribe("yt-remote-cast2-availability-change",function(a){g.DH("yt-remote-cast-available",a);g.$G("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){u9("onReceiverSelected: "+a.friendlyName);
g.DH("yt-remote-cast-receiver",a);g.$G("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){u9("onReceiverResumed: "+a.friendlyName);
g.DH("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){u9("onSessionChange: "+g.ZH(a));
a||g.FH("yt-remote-cast-receiver");g.$G("yt-remote-cast2-session-change",a)}),g.oa("yt.mdx.remote.cloudview.instance_",a,void 0),b=!0);
u9("cloudview.createSingleton_: "+b);return b},sva=function(){var a=0<=g.Hb.search(/\ (CrMo|Chrome|CriOS)\//);
return g.JG||a},$9=function(a,b){C9()?v9().setConnectedScreenStatus(a,b):E9("setConnectedScreenStatus called before ready.")},tva=function(){u9("clearCurrentReceiver");
g.FH("yt-remote-cast-receiver")},uva=function(){if(0<=window.navigator.userAgent.indexOf("CriOS")){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
if(a){lva();a({command:"cast.sender.init"});return}}if(window.chrome)if(lva(),a=window.navigator.userAgent,0<=a.indexOf("Android")&&0<=a.indexOf("Chrome/")&&window.navigator.presentation){var a="",b=g.Eh();55<=b?a="55":50<=b&&(a="50");g.Lh("//www.gstatic.com/eureka/clank"+a+g.Jh,g.Ih)}else g.Mh(0);else g.Ih()},vva=function(a){a?(g.DH("yt-remote-session-app",a.app),g.DH("yt-remote-session-name",a.name)):(g.FH("yt-remote-session-app"),g.FH("yt-remote-session-name"));
g.oa("yt.mdx.remote.channelParams_",a,void 0)},wva=function(){var a=H9();
if(g.Vb(a)){var a=g.hI(),b=g.EH("yt-remote-session-name")||"",c=g.EH("yt-remote-session-app")||"",a={device:"REMOTE_CONTROL",id:a,name:b,app:c,"mdx-version":3};g.oa("yt.mdx.remote.channelParams_",a,void 0)}},xva=function(){var a=N9();
a?(O9("Resume connection to: "+g.ZH(a)),M9(a,0)):(g.qI(),tva(),O9("Skipping connecting because no session screen found."))},yva=function(a){O9("remote.onCastSessionChange_: "+g.ZH(a));
if(a){var b=K9();b&&b.id==a.id?$9(b.id,"YouTube TV"):(b&&Q9(),M9(a,1))}else w9()&&Q9()},zva=function(){var a=mva(),b=K9();
b||(b=N9());return g.bb(a,function(a){return b&&g.WH(b,a.key)?!0:!1})},Ava=function(){var a=g.EH("yt-remote-cast-receiver");
return a?a.friendlyName:null},Bva=function(a,b,c,d){sva()?rva(b)&&(B9(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?hva(a,c):(window.__onGCastApiAvailable=function(b,d){b?hva(a,c):(E9("Failed to load cast API: "+d),D9(!1),B9(!1),g.FH("yt-remote-cast-available"),g.FH("yt-remote-cast-receiver"),cva(),c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):jva():uva())):u9("Cannot initialize because not running Chrome")},
Cva=function(a){this.port=this.A="";
this.g="/api/lounge";this.o=!0;a=a||window.document.location.href;var b=g.zg(a)||"";b&&(this.port=":"+b);this.A=g.yg(a)||"";a=g.Hb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ta(a,"10.0")&&(this.o=!1))},a$=function(a){g.X.call(this,{K:"div",
X:"ytp-remote",R:[{K:"div",X:"ytp-remote-display-status",R:[{K:"div",X:"ytp-remote-display-status-icon",R:[g.GE()]},{K:"div",X:"ytp-remote-display-status-text",R:["{{statustext}}"]},{K:"div",X:"ytp-remote-display-status-receiver",R:["{{receiver}}"]}]}]});this.g=new g.aW(this,250);g.M(this,this.g);this.A=a;this.V(a,"presentingplayerstatechange",this.B);Dva(this,g.zV(a))},Dva=function(a,b){if(3==a.A.Xa()){var c;
c=g.V(b,128)?g.U("YTP_MDX_STATUS_ERROR"):b.qb()||g.V(b,4)?g.U("YTP_MDX_STATUS_PLAYING"):g.U("YTP_MDX_STATUS_CONNECTED");var d=a.A.Xc("remote","currentReceiver");a.update({statustext:c,receiver:d.name});a.g.show()}else g.cW(a.g)},b$=function(a,b,c){g.L.call(this);
this.H=a;this.W=b;b.addEventListener("onVolumeChange",this.sn,this);b.addEventListener("onCaptionsTrackListChanged",this.Ry,this);b.addEventListener("captionschanged",this.Fy,this);b.addEventListener("captionssettingschanged",this.hs,this);b.addEventListener("videoplayerreset",this.Fk,this);b.addEventListener("mdxautoplaycancel",this.Eu,this);this.C=!1;this.g=c;c.subscribe("proxyStateChange",this.fz,this);c.subscribe("remotePlayerChange",this.Ek,this);c.subscribe("remoteQueueChange",this.Fk,this);
c.subscribe("autoplayUpNext",this.Dy,this);c.subscribe("previousNextChange",this.bz,this);c.subscribe("nowAutoplaying",this.Uy,this);c.subscribe("autoplayDismissed",this.Cy,this);this.suggestion=null;this.D=new g.kK(64);this.o=new g.ou(this.pA,500,this);g.M(this,this.o);this.A=new g.ou(this.qA,1E3,this);g.M(this,this.A);this.B={};this.G=new g.ou(this.EA,1E3,this);g.M(this,this.G);this.F=new g.uk(this.WR,1E3,this);g.M(this,this.F);this.J=g.x;this.hs();this.Fk();this.Ek()},c$=function(a,b){var c=a.H,
d=a.W.getVideoData().lengthSeconds;
c.H=b||0;c.g.U("progresssync",b,d)},Eva=function(a){c$(a,0);
a.o.stop();d$(a,new g.kK(64))},g$=function(a,b){if(e$(a)&&!a.C){var c=null;
b&&(c={style:a.W.il()},g.bc(c,b));a.g.jA(f$(a),c);a.B=T9(a.g).o}},h$=function(a,b){var c=a.W.df();
c?ova(a.g,f$(a),b,c.Rd(),c.listId.toString()):ova(a.g,f$(a),b);d$(a,new g.kK(1))},Fva=function(a,b){if(b){var c=a.W.Xc("captions","tracklist",{Uw:1});
c&&c.length?(a.W.Ge("captions","track",b),a.C=!1):(a.W.al("captions"),a.C=!0)}else a.W.Ge("captions","track",{})},e$=function(a){return T9(a.g).videoId==f$(a)},f$=function(a){return a.W.getVideoData().videoId},d$=function(a,b){a.A.stop();
var c=a.D;if(b.o!=c.o||b.g!=c.g){var d=g.V(b,2);if(d!=g.V(a.D,2)){var e=a.W;(e=g.yV(e.app,e.playerType||1))&&g.wU(e,d)}a.D=b;Gva(a.H,c,b)}},i$=function(){var a=zva();
!a&&F9()&&Ava()&&(a={key:"cast-selector-receiver",name:Ava()});return a},Hva=function(){var a=mva();
F9()&&g.EH("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},Iva=function(a){var b={device:"Desktop",
app:"youtube-desktop"};g.BH&&Yua();g.kI();L9||(L9=new Cva,g.sI()&&(L9.g="/api/loungedev"));I9||(I9=g.u("yt.mdx.remote.deferredProxies_")||[],g.oa("yt.mdx.remote.deferredProxies_",I9,void 0));wva();var c=A9();if(!c){var d=new g.DI(L9);g.oa("yt.mdx.remote.screenService_",d,void 0);c=A9();Bva(a,d,function(a){a?y9()&&$9(y9(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){g.$G("yt-remote-receiver-availability-change")})},!(!b||!b.loadCastApiSetupScript))}b&&!g.u("yt.mdx.remote.initialized_")&&
(g.oa("yt.mdx.remote.initialized_",!0,void 0),O9("Initializing: "+g.Nc(b)),j$.push(g.WG("yt-remote-cast2-availability-change",function(){g.$G("yt-remote-receiver-availability-change")})),j$.push(g.WG("yt-remote-cast2-receiver-selected",function(){x9(null);
g.$G("yt-remote-auto-connect","cast-selector-receiver")})),j$.push(g.WG("yt-remote-cast2-receiver-resumed",function(){g.$G("yt-remote-receiver-resumed","cast-selector-receiver")})),j$.push(g.WG("yt-remote-cast2-session-change",yva)),j$.push(g.WG("yt-remote-connection-change",function(a){a?$9(y9(),"YouTube TV"):N9()||($9(null,null),tva())})),a=H9(),b.isAuto&&(a.id+="#dial"),g.AG("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,O9(" -- with channel params: "+g.Nc(a)),
vva(a),c.start(),y9()||xva())},k$=function(){F9()?v9()?C9()?(u9("Requesting cast selector."),v9().requestSession()):(u9("Wait for cast API to be ready to request the session."),G9.push(g.WG("yt-remote-cast2-api-ready",k$))):E9("requestCastSelector: Cast is not initialized."):E9("requestCastSelector: Cast API is not installed!")},l$=function(a){g.XV.call(this,a);
this.A={key:g.aI(),name:g.U("YTP_MDX_MY_COMPUTER")};this.C=null;this.D=[];this.J=this.o=null;this.G=[this.A];this.B=this.A;this.F=new g.kK(64);this.H=0;var b=g.sV(a).C;b&&(b=b.A&&b.A.g)&&(b=new s9(a,b),g.M(this,b));b=new a$(a);g.M(this,b);g.RV(a,b.element,5)},Gva=function(a,b,c){a.F=c;
a.g.U("presentingplayerstatechange",new g.oU(c,b))},m$=function(a,b){if(b.key!=a.B.key)if(b.key==a.A.key)Q9();
else{a.B=b;var c;c=a.g.getPlaylistId();var d=a.g.getVideoData().videoId;if(c||d){var e,f=a.g.df();if(f){e=[];for(var k=0;k<f.getLength();k++)e[k]=f.Yb(k).videoId}else e=[a.g.getVideoData().videoId];c={videoIds:e,listId:c,videoId:d,index:Math.max(a.g.aB(),0),currentTime:a.g.getCurrentTime()}}else c=null;O9("Connecting to: "+g.Nc(b));"cast-selector-receiver"==b.key?(x9(c||null),c=c||null,C9()?v9().setLaunchParams(c):E9("setLaunchParams called before ready.")):!c&&P9()&&y9()==b.key?g.$G("yt-remote-connection-change",
!0):(Q9(),x9(c||null),c=A9().Td(),(c=g.cI(c,b.key))&&M9(c,1))}};
g.p(s9,g.AW);s9.prototype.H=function(){var a=this.W.Xc("remote","receivers");a&&1<a.length&&!this.W.Xc("remote","quickCast")?(this.G=g.Db(a,this.F,this),g.CW(this,(0,g.H)(a,this.F)),a=this.W.Xc("remote","currentReceiver"),g.BW(this,this.F(a)),this.B||(g.T1(this.g,this),this.B=!0)):this.B&&(g.U1(this.g,this),this.B=!1)};
s9.prototype.F=function(a){return a.key};
s9.prototype.Ne=function(a){return"cast-selector-receiver"==a?g.U("YTP_MDX_CAST_SELECTOR"):this.G[a].name};
s9.prototype.hd=function(a){g.AW.prototype.hd.call(this,a);this.W.Ge("remote","currentReceiver",this.G[a]);this.g.Vb()};
g.A(t9,g.dI);g.h=t9.prototype;g.h.Td=function(a){return this.Vc.$_gs(a)};
g.h.contains=function(a){return!!this.Vc.$_c(a)};
g.h.get=function(a){return this.Vc.$_g(a)};
g.h.start=function(){this.Vc.$_st()};
g.h.oo=function(a,b,c){this.Vc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Vc.$_r(a,b,c)};
g.h.Zn=function(a,b,c,d){this.Vc.$_un(a,b,c,d)};
g.h.P=function(){for(var a=0,b=this.o.length;a<b;++a)this.Vc.$_ubk(this.o[a]);this.o.length=0;this.Vc=null;t9.O.P.call(this)};
g.h.bQ=function(){this.U("screenChange")};
g.h.xM=function(){this.U("onlineScreenChange")};
var z9=null,G9=[],I9=null,L9=null;g.A(S9,g.uG);g.h=S9.prototype;g.h.play=function(){1==this.g?(this.o?this.o.play(null,g.x,Z9(this,"play")):U9(this,"play"),X9(this,1,g.$I(T9(this))),this.U("remotePlayerChange")):W9(this,this.play)};
g.h.pause=function(){1==this.g?(this.o?this.o.pause(null,g.x,Z9(this,"pause")):U9(this,"pause"),X9(this,2,g.$I(T9(this))),this.U("remotePlayerChange")):W9(this,this.pause)};
g.h.PA=function(a){if(1==this.g){if(this.o){var b=T9(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.qb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.o.seek(c,g.x,Z9(this,"seekTo",{newTime:a}))}else U9(this,"seekTo",{newTime:a});X9(this,3,a);this.U("remotePlayerChange")}else W9(this,g.za(this.PA,a))};
g.h.stop=function(){if(1==this.g){this.o?this.o.stop(null,g.x,Z9(this,"stopVideo")):U9(this,"stopVideo");var a=T9(this);a.index=-1;a.videoId="";g.YI(a);V9(this,a);this.U("remotePlayerChange")}else W9(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=T9(this);if(this.A){if(c.volume!=a){var d=Math.round(a)/100;this.A.setReceiverVolumeLevel(d,(0,g.z)(function(){Y9("set receiver volume: "+d)},this),(0,g.z)(function(){this.ac("failed to set receiver volume.")},this))}c.muted!=b&&this.A.setReceiverMuted(b,(0,g.z)(function(){Y9("set receiver muted: "+b)},this),(0,g.z)(function(){this.ac("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);U9(this,"setVolume",e)}c.muted=b;c.volume=a;V9(this,c)}else W9(this,g.za(this.setVolume,a,b))};
g.h.jA=function(a,b){if(1==this.g){var c=T9(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.Nc(b.style),g.bc(d,c.o));U9(this,"setSubtitlesTrack",d);V9(this,c)}else W9(this,g.za(this.jA,a,b))};
g.h.Ps=function(a,b){if(1==this.g){U9(this,"setAudioTrack",{videoId:a,audioTrackId:b.Lc.id});var c=T9(this);c.audioTrackId=b.Lc.id;V9(this,c)}else W9(this,g.za(this.Ps,a,b))};
g.h.OA=function(a,b){if(1==this.g){if(a&&b){var c=T9(this);g.aJ(c,a,b);V9(this,c)}U9(this,"previous")}else W9(this,g.za(this.OA,a,b))};
g.h.NA=function(a,b){if(1==this.g){if(a&&b){var c=T9(this);g.aJ(c,a,b);V9(this,c)}U9(this,"next")}else W9(this,g.za(this.NA,a,b))};
g.h.rv=function(){1==this.g?U9(this,"dismissAutoplay"):W9(this,this.rv)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.U("proxyStateChange",a,this.g)}S9.O.dispose.call(this)};
g.h.P=function(){pva(this);this.B=null;this.C.clear();R9(this,null);S9.O.P.call(this)};
g.h.Qs=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.U("proxyStateChange",b,a);if(1==a)for(;!this.C.isEmpty();)g.qC(this.C).apply(this);else 3==a&&this.dispose()}};
g.h.RM=function(a,b){this.U(a,b)};
g.h.IK=function(a){if(!a)this.Ck(null),R9(this,null);else if(this.A.receiver.volume){a=this.A.receiver.volume;var b=T9(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)Y9("Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,V9(this,b)}};
g.h.Ck=function(a){Y9("Cast media: "+!!a);this.o&&this.o.removeUpdateListener(this.G);if(this.o=a)this.o.addUpdateListener(this.G),qva(this),this.U("remotePlayerChange")};
g.h.HK=function(a){a?(qva(this),this.U("remotePlayerChange")):this.Ck(null)};
g.h.VK=function(){var a=iva();a&&R9(this,a)};
g.h.ac=function(a){g.RH("CP",a)};
var j$=[];g.h=Cva.prototype;g.h.Gh=function(a,b,c){var d=this.g;if(g.t(c)?c:this.o)d="https://"+this.A+this.port+this.g;return g.Hg(d+a,b||{})};
g.h.Os=function(a,b,c,d){c={format:"JSON",method:"POST",context:this,timeout:5E3,withCredentials:!1,Jb:g.za(this.WP,c,!0),onError:g.za(this.VP,d),gd:g.za(this.XP,d)};b&&(c.Ob=b,c.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.xF(a,c)};
g.h.WP=function(a,b,c,d){b?a(d):a({text:c.responseText})};
g.h.VP=function(a,b){a(Error("Request error: "+b.status))};
g.h.XP=function(a){a(Error("request timed out"))};
g.p(a$,g.X);a$.prototype.B=function(a){Dva(this,a.state)};
g.A(b$,g.L);g.h=b$.prototype;
g.h.P=function(){b$.O.P.call(this);this.o.stop();this.A.stop();this.J();this.W.removeEventListener("onVolumeChange",this.sn,this);this.W.removeEventListener("onCaptionsTrackListChanged",this.Ry,this);this.W.removeEventListener("captionschanged",this.Fy,this);this.W.removeEventListener("videoplayerreset",this.Fk,this);this.W.removeEventListener("captionssettingschanged",this.hs,this);this.W.removeEventListener("mdxautoplaycancel",this.Eu,this);this.g.unsubscribe("proxyStateChange",this.fz,this);this.g.unsubscribe("remotePlayerChange",
this.Ek,this);this.g.unsubscribe("remoteQueueChange",this.Fk,this);this.g.unsubscribe("autoplayUpNext",this.Dy,this);this.g.unsubscribe("previousNextChange",this.bz,this);this.g.unsubscribe("nowAutoplaying",this.Uy,this);this.g.unsubscribe("autoplayDismissed",this.Cy,this);this.g=this.H=null};
g.h.DB=function(a,b){2==this.g.g||(e$(this)?this.yG.apply(this,arguments):this.uG.apply(this,arguments))};
g.h.Fy=function(a){this.DB("control_subtitles_set_track",g.Vb(a)?null:a)};
g.h.hs=function(){var a=this.W.Xc("captions","track");g.Vb(a)||g$(this,a)};
g.h.uG=function(a,b){var c=Array.prototype.slice.call(arguments,1);switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":h$(this,this.W.getCurrentTime());break;case "control_seek":h$(this,c[0]);break;case "control_subtitles_set_track":g$(this,c[0]);break;case "control_set_audio_track":c=c[0],e$(this)&&this.g.Ps(f$(this),c)}};
g.h.yG=function(a,b){if(1081!=T9(this.g).g||"control_seek"!=a){var c=Array.prototype.slice.call(arguments,1);switch(a){case "control_toggle_play_pause":T9(this.g).qb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.F.Mi(c[0],c[1]);break;case "control_subtitles_set_track":g$(this,c[0]);break;case "control_set_audio_track":c=c[0],e$(this)&&this.g.Ps(f$(this),c)}}};
g.h.sn=function(a){if(e$(this)){this.g.unsubscribe("remotePlayerChange",this.Ek,this);var b=Math.round(a.volume);a=!!a.muted;var c=T9(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.G.start();this.g.subscribe("remotePlayerChange",this.Ek,this)}};
g.h.Ry=function(){g.Vb(this.B)||Fva(this,this.B);this.C=!1};
g.h.fz=function(a,b){this.A.stop();2==b&&this.qA()};
g.h.Ek=function(){if(e$(this)){this.o.stop();var a=T9(this.g);switch(a.g){case 1081:d$(this,new g.kK(8));break;case 1:this.pA();d$(this,new g.kK(8));break;case 1083:case 3:d$(this,new g.kK(9));break;case 0:d$(this,new g.kK(2));this.F.stop();c$(this,this.W.getVideoData().lengthSeconds);break;case 1082:d$(this,new g.kK(4));break;case 2:d$(this,new g.kK(4));c$(this,g.$I(a));break;case -1:d$(this,new g.kK(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.U("YTP_MDX_PLAYER_ERROR")},d$(this,
new g.kK(128,a))}var a=T9(this.g).o,b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.B=a,Fva(this,a));a=T9(this.g);-1==a.volume||Math.round(this.W.getVolume())==a.volume&&this.W.ae()==a.muted||this.G.isActive()||this.EA()}else Eva(this)};
g.h.bz=function(){this.W.U("mdxpreviousnextchange")};
g.h.Fk=function(){e$(this)||Eva(this)};
g.h.Eu=function(){this.g.rv()};
g.h.Dy=function(a){a&&(a=g.xF("/watch_queue_ajax",{method:"GET",Hc:{action_get_watch_queue_item:1,video_id:a},Jb:(0,g.z)(this.PN,this)}))&&(this.J=(0,g.z)(a.abort,a))};
g.h.PN=function(a,b){var c=new g.RQ({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.W.U("mdxautoplayupnext",c)};
g.h.Uy=function(a){(0,window.isNaN)(a)||this.W.U("mdxnowautoplaying",a)};
g.h.Cy=function(){this.W.U("mdxautoplaycanceled")};
g.h.WR=function(a,b){-1==T9(this.g).g?h$(this,a):b&&this.g.PA(a)};
g.h.EA=function(){if(e$(this)){var a=T9(this.g);this.W.removeEventListener("onVolumeChange",this.sn,this);a.muted?this.W.mute():this.W.zg();this.W.setVolume(a.volume);this.W.addEventListener("onVolumeChange",this.sn,this)}};
g.h.pA=function(){this.o.stop();if(!this.g.la()){var a=T9(this.g);a.qb()&&d$(this,new g.kK(8));c$(this,g.$I(a));this.o.start()}};
g.h.qA=function(){this.A.stop();this.o.stop();var a=this.g.B.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.A.start()};
g.A(l$,g.XV);g.h=l$.prototype;g.h.create=function(){Iva("embedded"==g.Y(this.g).g);this.D.push(g.WG("yt-remote-before-disconnect",this.EK,this));this.D.push(g.WG("yt-remote-connection-change",this.aN,this));this.D.push(g.WG("yt-remote-receiver-availability-change",this.dz,this));this.D.push(g.WG("yt-remote-auto-connect",this.YM,this));this.D.push(g.WG("yt-remote-receiver-resumed",this.XM,this));this.dz()};
g.h.load=function(){this.g.pp();l$.O.load.call(this);this.C=new b$(this,this.g,this.o);var a;a=(a=gva())?a.currentTime:0;var b=P9()?new S9(w9(),void 0):null;0==a&&b&&(a=g.$I(T9(b)));0!=a&&(this.H=a||0,this.g.U("progresssync",a,void 0));Gva(this,this.F,this.F);g.S2(this.g.app,6)};
g.h.unload=function(){this.g.U("mdxautoplaycanceled");this.B=this.A;g.We(this.C,this.o);this.o=this.C=null;l$.O.unload.call(this);g.S2(this.g.app,5)};
g.h.P=function(){(0,g.r2)(this.D);l$.O.P.call(this)};
g.h.nl=function(a,b){this.loaded&&this.C.DB.apply(this.C,arguments)};
g.h.ZF=function(){return this.loaded?this.C.suggestion:null};
g.h.Cf=function(){return this.o?T9(this.o).Cf:!1};
g.h.hasNext=function(){return this.o?T9(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.H};
g.h.AR=function(){var a=T9(this.o),b=this.g.getVideoData(),c=this.g.Ed(),d=b.clipEnd,b=b.clipStart,e=this.getCurrentTime(),f=a.getDuration(),k;k=a.H?a.B+((0,g.E)()-a.A)/1E3:a.B;var l=1>=Xua(a)-this.getCurrentTime(),m=a.J,n=Xua(a),a=0<a.C?a.C+((0,g.E)()-a.A)/1E3:a.C;return{allowSeeking:c,clipEnd:d,clipStart:b,current:e,displayedStart:-1,duration:f,ingestionTime:k,isPeggedToLive:l,loaded:m,seekableEnd:n,seekableStart:a}};
g.h.CR=function(){this.o&&this.o.NA()};
g.h.DR=function(){this.o&&this.o.OA()};
g.h.EK=function(a){1==a&&(this.J=this.o?T9(this.o):null)};
g.h.aN=function(){var a=P9()?new S9(w9(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.J=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.Ve(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.J)&&a.videoId==this.g.getVideoData().videoId&&this.g.Rc(g.$I(a)));this.g.U("videodatachange","newdata",this.g.getVideoData(),3)};
g.h.dz=function(){this.G=[this.A].concat(Hva());var a=i$()||this.A;m$(this,a);this.g.xa("onMdxReceiversChange")};
g.h.YM=function(){var a=i$();m$(this,a)};
g.h.XM=function(){this.B=i$()};
g.h.zR=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.G;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?k$():m$(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.G.length&&"cast-selector-receiver"==this.G[1].key?(b&&k$(),!0):!1}};
g.h.ER=function(){U9(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Ae=function(){return!1};
window._exportCheck==g.Ca&&g.oa("ytmod.player.remote",l$,void 0);})(_yt_player);
